services:
  api:
    environment:
      CONNECTOR_KEY_RING: !reset null
      CONNECTOR_KEY_RING_FILE: /run/secrets/connector_key_ring
    secrets:
      - source: connector_key_ring
        target: connector_key_ring

  worker:
    environment:
      CONNECTOR_KEY_RING: !reset null
      CONNECTOR_KEY_RING_FILE: /run/secrets/connector_key_ring
    secrets:
      - source: connector_key_ring
        target: connector_key_ring

secrets:
  connector_key_ring:
    file: ${SECRETS_DIRECTORY:?SECRETS_DIRECTORY is required}/connector_key_ring
