import { z } from "zod";
import {
  ConnectorError,
  connectorContractVersion,
  defineConnector,
  failureForStatus,
  type IngressRequest,
  type IngressResult
} from "../contract.js";

/**
 * The reference connector: it accepts signed events from any provider that can post JSON.
 *
 * It exists to keep the contract honest. Every rule the platform claims to enforce — allowlisted
 * configuration, a capability manifest that actually limits, signature verification owned by the
 * API, idempotency by the provider's own event id — is exercised here, so a rule that stops
 * being true breaks a test rather than a customer's integration in Phase 7.
 */

const configSchema = z.strictObject({
  /**
   * Optional, because an inbound-only integration is the ordinary case and most providers offer
   * nothing to ask. Without it the health check reports `unverifiable` rather than inventing a pass.
   */
  healthUrl: z.url().startsWith("https://").max(2048).optional(),
  /** Where the provider's own event id sits in the payload, as a dotted path. */
  eventIdPath: z.string().min(1).max(120).default("id"),
  eventTypePath: z.string().min(1).max(120).default("type"),
  /** Empty keeps everything. Anything else is an allowlist of event types worth storing. */
  eventTypes: z.array(z.string().min(1).max(80)).max(50).default([])
});

export type GenericWebhookConfig = z.infer<typeof configSchema>;

/**
 * Segments that would walk out of the payload and into the prototype chain.
 *
 * `JSON.parse` does create an own property called `__proto__` when the text contains one, so a
 * configured path of `__proto__.polluted` would otherwise read something an attacker placed
 * there. Reading is far less dangerous than assigning, but a deny-list here costs one line.
 */
const unsafeSegments = new Set(["__proto__", "constructor", "prototype"]);

function readPath(payload: unknown, path: string): unknown {
  let current: unknown = payload;
  for (const segment of path.split(".")) {
    if (unsafeSegments.has(segment)) return undefined;
    if (typeof current !== "object" || current === null) return undefined;
    const record = current as Record<string, unknown>;
    if (!Object.hasOwn(record, segment)) return undefined;
    current = record[segment];
  }
  return current;
}

/** A string worth keeping: present, non-empty and short enough to store beside the event. */
function boundedString(value: unknown, maxLength: number): string | null {
  if (typeof value !== "string") return null;
  return value.length > 0 && value.length <= maxLength ? value : null;
}

function readEvent(config: GenericWebhookConfig, request: IngressRequest): IngressResult {
  let payload: unknown;
  try {
    payload = JSON.parse(request.body);
  } catch {
    throw new ConnectorError("INVALID_PAYLOAD");
  }

  const eventId = boundedString(readPath(payload, config.eventIdPath), 200);
  const eventType = boundedString(readPath(payload, config.eventTypePath), 80);
  // An event with no type cannot match an allowlist, so a configured allowlist filters it out.
  const accepted = config.eventTypes.length === 0 || (eventType !== null && config.eventTypes.includes(eventType));

  return { eventId, accepted, summary: eventType ? { eventType } : {} };
}

export const genericWebhook = defineConnector<GenericWebhookConfig>({
  type: "generic-webhook",
  contractVersion: connectorContractVersion,
  configSchema,
  /** The signing secret is generated by us and sealed; the provider never gives us one. */
  credentialKinds: ["ingress_signing"],
  capabilities: {
    egress: { schemes: ["https"], destination: "configured_base_url" },
    /** No outbound operations: this connector receives, it does not go and fetch. */
    operations: [],
    ingress: true
  },
  async health(context) {
    const healthUrl = context.config.healthUrl;
    if (!healthUrl) return { status: "unverifiable" };

    const response = await context.http.send({ method: "GET", url: healthUrl, timeoutMs: 10_000 });
    const failure = failureForStatus(response.status);
    return failure ? { status: "failed", failure } : { status: "ok" };
  },
  operations: {},
  ingress: {
    signature: {
      algorithm: "hmac-sha256",
      signatureHeader: "x-control-hub-signature",
      timestampHeader: "x-control-hub-timestamp",
      /**
       * The timestamp is inside the signed bytes on purpose. Signing the body alone would let
       * somebody replay a valid request with a fresh timestamp header and pass both the
       * signature check and the replay window.
       */
      payload: (timestamp, rawBody) => `${timestamp}.${rawBody}`
    },
    handle: (context, request) => readEvent(context.config, request)
  }
});
