/**
 * Turns a release manifest into the `release.env` that `compose.release.yaml` reads.
 *
 *   node scripts/release-env.mjs --manifest release.json --out release.env
 *
 * The whole file is rewritten every time, and that is the design rather than a shortcut. An update
 * that edited variables in place would leave behind whatever the previous version had and no
 * longer needs, and a stale image reference is the one kind of leftover that still works -- it
 * pulls, it starts, and it runs the old code under the new version number.
 *
 * `.env` is never touched. What an operator configured by hand and what a release decides are two
 * different files precisely so that upgrading cannot lose the first one.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { manifestEnvironment, parseManifest } from "./release-manifest.mjs";

const header = [
  "# Generated by scripts/release-env.mjs from the release manifest. Do not edit.",
  "# Rewritten in full on every update; your own settings belong in .env, which updates never touch."
];

export function releaseEnvironment(manifestText) {
  return [...header, ...manifestEnvironment(parseManifest(manifestText))].join("\n") + "\n";
}

function argument(name) {
  const index = process.argv.indexOf(`--${name}`);
  return index === -1 ? undefined : process.argv[index + 1];
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const manifest = argument("manifest") ?? "release.json";
  const out = argument("out") ?? "release.env";
  const contents = releaseEnvironment(readFileSync(manifest, "utf8"));
  writeFileSync(out, contents);
  process.stdout.write(contents);
}
