export const locales = ["ca", "es", "en"] as const;
export type Locale = (typeof locales)[number];
export const defaultLocale: Locale = "ca";

const dictionaries = {
  ca: {
    navigation: { label: "Navegacio principal", dashboard: "Dashboard", customers: "Clients", products: "Productes", subscriptions: "Subscripcions", support: "Suport", infrastructure: "Infraestructura", integrations: "Integracions", settings: "Configuracio" },
    header: { search: "Cerca global", healthy: "Sistema preparat", theme: "Canviar tema", language: "Idioma", account: "Compte" },
    dashboard: { eyebrow: "OPERACIONS EN TEMPS REAL", title: "Centre de control", description: "Visio unificada del negoci, serveis i automatitzacions.", revenue: "Ingressos recurrents", customers: "Clients actius", incidents: "Incidencies obertes", automations: "Automatitzacions", companyHealth: "Salut de l'empresa", activity: "Activitat recent", noData: "Les metriques apareixeran quan connectem les primeres fonts.", ready: "Fonaments preparats" },
    crm: { eyebrow: "RELACIONS COMERCIALS", title: "CRM", description: "Leads, clients i activitat comercial centralitzats.", leads: "Leads", customers: "Clients", addLead: "Afegir lead", search: "Cercar per nom, correu o telefon", name: "Nom", company: "Empresa", email: "Correu", phone: "Telefon", source: "Origen", priority: "Prioritat", status: "Estat", created: "Creat", actions: "Accions", save: "Desar lead", cancel: "Cancel·lar", convert: "Convertir en client", emptyLeads: "Encara no hi ha leads.", emptyCustomers: "Encara no hi ha clients.", loadError: "No s'han pogut carregar les dades del CRM.", new: "Nou", contacted: "Contactat", qualified: "Qualificat", proposal: "Proposta", won: "Guanyat", lost: "Perdut", low: "Baixa", normal: "Normal", high: "Alta", urgent: "Urgent", manual: "Manual", next: "Avancar estat" }
    ,auth: { title: "Accedeix a Control Hub", subtitle: "Operacions, infraestructura i seguretat en un sol lloc.", email: "Correu electronic", password: "Contrasenya", signIn: "Iniciar sessio", otp: "Codi de verificacio", verify: "Verificar", forgot: "Has oblidat la contrasenya?", error: "No s'ha pogut iniciar la sessio.", resetTitle: "Restablir contrasenya", sendLink: "Enviar enllac", sent: "Si el compte existeix, rebras un correu.", newPassword: "Nova contrasenya", updatePassword: "Actualitzar contrasenya" },
    security: { title: "Seguretat del compte", secondFactor: "Segon factor", mfaDescription: "Activa TOTP per accedir als moduls protegits.", sessions: "Sessions actives", signOut: "Tancar sessio", revoke: "Revocar", currentPassword: "Contrasenya actual", enableTotp: "Activar TOTP", addPasskey: "Afegir passkey", unknownDevice: "Dispositiu desconegut", unknownIp: "IP desconeguda", backupCodes: "Codis de recuperacio", scanQr: "Escaneja el QR amb Google Authenticator o una aplicacio TOTP i confirma el primer codi.", verificationCode: "Codi de 6 digits", confirmTotp: "Confirmar TOTP", backupWarning: "Desa aquests codis en un lloc segur. Cada codi nomes es pot utilitzar una vegada.", totpEnabled: "TOTP esta activat i protegeix els moduls privilegiats." },
    invitations: { title: "Membres i invitacions", description: "Convida usuaris al tenant actual. Els enllacos caduquen al cap de 48 hores i son d'un sol us.", role: "Rol", technical: "Tecnic", administrator: "Administrador", send: "Enviar invitacio", revoke: "Revocar invitacio", error: "No s'ha pogut enviar la invitacio.", invalid: "La invitacio no existeix, ha caducat o ja s'ha utilitzat.", acceptTitle: "Accepta la invitacio", name: "Nom complet", accept: "Crear compte", accepted: "Compte creat", verifyEmail: "Revisa el correu i verifica l'adreca abans d'iniciar sessio.", acceptError: "No s'ha pogut crear el compte. Comprova les dades o demana una invitacio nova." }
  },
  es: {
    navigation: { label: "Navegacion principal", dashboard: "Dashboard", customers: "Clientes", products: "Productos", subscriptions: "Suscripciones", support: "Soporte", infrastructure: "Infraestructura", integrations: "Integraciones", settings: "Configuracion" },
    header: { search: "Busqueda global", healthy: "Sistema preparado", theme: "Cambiar tema", language: "Idioma", account: "Cuenta" },
    dashboard: { eyebrow: "OPERACIONES EN TIEMPO REAL", title: "Centro de control", description: "Vision unificada del negocio, servicios y automatizaciones.", revenue: "Ingresos recurrentes", customers: "Clientes activos", incidents: "Incidencias abiertas", automations: "Automatizaciones", companyHealth: "Salud de la empresa", activity: "Actividad reciente", noData: "Las metricas apareceran al conectar las primeras fuentes.", ready: "Fundamentos preparados" },
    crm: { eyebrow: "RELACIONES COMERCIALES", title: "CRM", description: "Leads, clientes y actividad comercial centralizados.", leads: "Leads", customers: "Clientes", addLead: "Anadir lead", search: "Buscar por nombre, correo o telefono", name: "Nombre", company: "Empresa", email: "Correo", phone: "Telefono", source: "Origen", priority: "Prioridad", status: "Estado", created: "Creado", actions: "Acciones", save: "Guardar lead", cancel: "Cancelar", convert: "Convertir en cliente", emptyLeads: "Todavia no hay leads.", emptyCustomers: "Todavia no hay clientes.", loadError: "No se han podido cargar los datos del CRM.", new: "Nuevo", contacted: "Contactado", qualified: "Cualificado", proposal: "Propuesta", won: "Ganado", lost: "Perdido", low: "Baja", normal: "Normal", high: "Alta", urgent: "Urgente", manual: "Manual", next: "Avanzar estado" }
    ,auth: { title: "Accede a Control Hub", subtitle: "Operaciones, infraestructura y seguridad en un solo lugar.", email: "Correo electronico", password: "Contrasena", signIn: "Iniciar sesion", otp: "Codigo de verificacion", verify: "Verificar", forgot: "Has olvidado la contrasena?", error: "No se ha podido iniciar sesion.", resetTitle: "Restablecer contrasena", sendLink: "Enviar enlace", sent: "Si la cuenta existe, recibiras un correo.", newPassword: "Nueva contrasena", updatePassword: "Actualizar contrasena" },
    security: { title: "Seguridad de la cuenta", secondFactor: "Segundo factor", mfaDescription: "Activa TOTP para acceder a los modulos protegidos.", sessions: "Sesiones activas", signOut: "Cerrar sesion", revoke: "Revocar", currentPassword: "Contrasena actual", enableTotp: "Activar TOTP", addPasskey: "Anadir passkey", unknownDevice: "Dispositivo desconocido", unknownIp: "IP desconocida", backupCodes: "Codigos de recuperacion", scanQr: "Escanea el QR con Google Authenticator o una aplicacion TOTP y confirma el primer codigo.", verificationCode: "Codigo de 6 digitos", confirmTotp: "Confirmar TOTP", backupWarning: "Guarda estos codigos en un lugar seguro. Cada codigo solo puede utilizarse una vez.", totpEnabled: "TOTP esta activado y protege los modulos privilegiados." },
    invitations: { title: "Miembros e invitaciones", description: "Invita usuarios al tenant actual. Los enlaces caducan en 48 horas y son de un solo uso.", role: "Rol", technical: "Tecnico", administrator: "Administrador", send: "Enviar invitacion", revoke: "Revocar invitacion", error: "No se ha podido enviar la invitacion.", invalid: "La invitacion no existe, ha caducado o ya se ha utilizado.", acceptTitle: "Acepta la invitacion", name: "Nombre completo", accept: "Crear cuenta", accepted: "Cuenta creada", verifyEmail: "Revisa el correo y verifica la direccion antes de iniciar sesion.", acceptError: "No se ha podido crear la cuenta. Comprueba los datos o solicita una invitacion nueva." }
  },
  en: {
    navigation: { label: "Primary navigation", dashboard: "Dashboard", customers: "Customers", products: "Products", subscriptions: "Subscriptions", support: "Support", infrastructure: "Infrastructure", integrations: "Integrations", settings: "Settings" },
    header: { search: "Global search", healthy: "System ready", theme: "Change theme", language: "Language", account: "Account" },
    dashboard: { eyebrow: "REAL-TIME OPERATIONS", title: "Control center", description: "A unified view of business, services and automations.", revenue: "Recurring revenue", customers: "Active customers", incidents: "Open incidents", automations: "Automations", companyHealth: "Company health", activity: "Recent activity", noData: "Metrics will appear after the first sources are connected.", ready: "Foundations ready" },
    crm: { eyebrow: "COMMERCIAL RELATIONSHIPS", title: "CRM", description: "Centralized leads, customers and commercial activity.", leads: "Leads", customers: "Customers", addLead: "Add lead", search: "Search by name, email or phone", name: "Name", company: "Company", email: "Email", phone: "Phone", source: "Source", priority: "Priority", status: "Status", created: "Created", actions: "Actions", save: "Save lead", cancel: "Cancel", convert: "Convert to customer", emptyLeads: "There are no leads yet.", emptyCustomers: "There are no customers yet.", loadError: "CRM data could not be loaded.", new: "New", contacted: "Contacted", qualified: "Qualified", proposal: "Proposal", won: "Won", lost: "Lost", low: "Low", normal: "Normal", high: "High", urgent: "Urgent", manual: "Manual", next: "Advance status" }
    ,auth: { title: "Access Control Hub", subtitle: "Operations, infrastructure and security in one place.", email: "Email address", password: "Password", signIn: "Sign in", otp: "Verification code", verify: "Verify", forgot: "Forgot your password?", error: "Unable to sign in.", resetTitle: "Reset password", sendLink: "Send link", sent: "If the account exists, you will receive an email.", newPassword: "New password", updatePassword: "Update password" },
    security: { title: "Account security", secondFactor: "Second factor", mfaDescription: "Enable TOTP to access protected modules.", sessions: "Active sessions", signOut: "Sign out", revoke: "Revoke", currentPassword: "Current password", enableTotp: "Enable TOTP", addPasskey: "Add passkey", unknownDevice: "Unknown device", unknownIp: "Unknown IP", backupCodes: "Backup codes", scanQr: "Scan the QR with Google Authenticator or another TOTP app and confirm the first code.", verificationCode: "6-digit code", confirmTotp: "Confirm TOTP", backupWarning: "Store these codes securely. Each code can only be used once.", totpEnabled: "TOTP is enabled and protects privileged modules." },
    invitations: { title: "Members and invitations", description: "Invite users to the current tenant. Links expire after 48 hours and can only be used once.", role: "Role", technical: "Technical", administrator: "Administrator", send: "Send invitation", revoke: "Revoke invitation", error: "The invitation could not be sent.", invalid: "The invitation does not exist, has expired, or has already been used.", acceptTitle: "Accept invitation", name: "Full name", accept: "Create account", accepted: "Account created", verifyEmail: "Check your email and verify the address before signing in.", acceptError: "The account could not be created. Check the details or request a new invitation." }
  }
} as const;

export function isLocale(value: string): value is Locale { return locales.includes(value as Locale); }
export function getDictionary(locale: Locale) { return dictionaries[locale]; }

const crmDetailDictionaries = {
  ca: { contacts: "Contactes", notes: "Notes", tasks: "Tasques", timeline: "Activitat", addContact: "Afegir contacte", addNote: "Afegir nota", addTask: "Afegir tasca", role: "Carrec", primary: "Principal", dueAt: "Venciment", complete: "Completar", back: "Tornar al CRM", exportCsv: "Exportar CSV", importCsv: "Importar CSV", preview: "Previsualitzar", import: "Importar", activeCustomers: "Clients actius", openTasks: "Tasques obertes", overdueTasks: "Tasques vencudes", pipeline: "Pipeline comercial" },
  es: { contacts: "Contactos", notes: "Notas", tasks: "Tareas", timeline: "Actividad", addContact: "Anadir contacto", addNote: "Anadir nota", addTask: "Anadir tarea", role: "Cargo", primary: "Principal", dueAt: "Vencimiento", complete: "Completar", back: "Volver al CRM", exportCsv: "Exportar CSV", importCsv: "Importar CSV", preview: "Previsualizar", import: "Importar", activeCustomers: "Clientes activos", openTasks: "Tareas abiertas", overdueTasks: "Tareas vencidas", pipeline: "Pipeline comercial" },
  en: { contacts: "Contacts", notes: "Notes", tasks: "Tasks", timeline: "Activity", addContact: "Add contact", addNote: "Add note", addTask: "Add task", role: "Role", primary: "Primary", dueAt: "Due date", complete: "Complete", back: "Back to CRM", exportCsv: "Export CSV", importCsv: "Import CSV", preview: "Preview", import: "Import", activeCustomers: "Active customers", openTasks: "Open tasks", overdueTasks: "Overdue tasks", pipeline: "Commercial pipeline" }
} as const;
export function getCrmDetailDictionary(locale: Locale) { return crmDetailDictionaries[locale]; }

const commerceDictionaries = {
  ca: { eyebrow: "OFERTA I INGRESSOS", title: "Productes i subscripcions", description: "Cataleg versionat, contractes recurrents, renovacions i marges auditables.", catalog: "Cataleg", subscriptions: "Subscripcions", product: "Producte", products: "Productes", version: "Versio", versions: "Versions", plan: "Pla", plans: "Plans", price: "Preu", prices: "Preus", addProduct: "Afegir producte", addVersion: "Afegir versio", addPlan: "Afegir pla", publishPrice: "Publicar preu", addSubscription: "Nova subscripcio", code: "Codi", name: "Nom", descriptionLabel: "Descripcio", status: "Estat", currency: "Moneda", netPrice: "Preu net", cost: "Cost", tax: "Impost (%)", interval: "Periodicitat", effectiveFrom: "Efectiu des de", customer: "Client", quantity: "Quantitat", renewalAt: "Proxima renovacio", alertDays: "Avis previ (dies)", save: "Desar", active: "Activa", paused: "Pausada", canceled: "Cancel·lada", pause: "Pausar", resume: "Reprendre", cancel: "Cancel·lar", changePlan: "Canviar pla", monthly: "Mensual", quarterly: "Trimestral", semiannual: "Semestral", annual: "Anual", free: "Gratuit", draft: "Esborrany", mrr: "MRR net", arr: "ARR net", annualCost: "Cost anual", margin: "Marge anual", renewals: "Renovacions properes", noRenewals: "No hi ha renovacions dins la finestra d'alerta.", emptyCatalog: "Crea el primer producte per iniciar el cataleg.", emptySubscriptions: "Encara no hi ha subscripcions.", loadError: "No s'han pogut carregar les dades comercials.", formError: "No s'ha pogut completar l'operacio.", amountHelp: "Imports en unitats principals; es desaran en centims.", releasedAt: "Data de publicacio" },
  es: { eyebrow: "OFERTA E INGRESOS", title: "Productos y suscripciones", description: "Catalogo versionado, contratos recurrentes, renovaciones y margenes auditables.", catalog: "Catalogo", subscriptions: "Suscripciones", product: "Producto", products: "Productos", version: "Version", versions: "Versiones", plan: "Plan", plans: "Planes", price: "Precio", prices: "Precios", addProduct: "Anadir producto", addVersion: "Anadir version", addPlan: "Anadir plan", publishPrice: "Publicar precio", addSubscription: "Nueva suscripcion", code: "Codigo", name: "Nombre", descriptionLabel: "Descripcion", status: "Estado", currency: "Moneda", netPrice: "Precio neto", cost: "Coste", tax: "Impuesto (%)", interval: "Periodicidad", effectiveFrom: "Efectivo desde", customer: "Cliente", quantity: "Cantidad", renewalAt: "Proxima renovacion", alertDays: "Aviso previo (dias)", save: "Guardar", active: "Activa", paused: "Pausada", canceled: "Cancelada", pause: "Pausar", resume: "Reanudar", cancel: "Cancelar", changePlan: "Cambiar plan", monthly: "Mensual", quarterly: "Trimestral", semiannual: "Semestral", annual: "Anual", free: "Gratuito", draft: "Borrador", mrr: "MRR neto", arr: "ARR neto", annualCost: "Coste anual", margin: "Margen anual", renewals: "Proximas renovaciones", noRenewals: "No hay renovaciones dentro de la ventana de aviso.", emptyCatalog: "Crea el primer producto para iniciar el catalogo.", emptySubscriptions: "Todavia no hay suscripciones.", loadError: "No se han podido cargar los datos comerciales.", formError: "No se ha podido completar la operacion.", amountHelp: "Importes en unidades principales; se guardaran en centimos.", releasedAt: "Fecha de publicacion" },
  en: { eyebrow: "OFFERING AND REVENUE", title: "Products and subscriptions", description: "Versioned catalog, recurring contracts, renewals and auditable margins.", catalog: "Catalog", subscriptions: "Subscriptions", product: "Product", products: "Products", version: "Version", versions: "Versions", plan: "Plan", plans: "Plans", price: "Price", prices: "Prices", addProduct: "Add product", addVersion: "Add version", addPlan: "Add plan", publishPrice: "Publish price", addSubscription: "New subscription", code: "Code", name: "Name", descriptionLabel: "Description", status: "Status", currency: "Currency", netPrice: "Net price", cost: "Cost", tax: "Tax (%)", interval: "Billing interval", effectiveFrom: "Effective from", customer: "Customer", quantity: "Quantity", renewalAt: "Next renewal", alertDays: "Advance notice (days)", save: "Save", active: "Active", paused: "Paused", canceled: "Canceled", pause: "Pause", resume: "Resume", cancel: "Cancel", changePlan: "Change plan", monthly: "Monthly", quarterly: "Quarterly", semiannual: "Semiannual", annual: "Annual", free: "Free", draft: "Draft", mrr: "Net MRR", arr: "Net ARR", annualCost: "Annual cost", margin: "Annual margin", renewals: "Upcoming renewals", noRenewals: "No renewals fall within the alert window.", emptyCatalog: "Create the first product to start the catalog.", emptySubscriptions: "There are no subscriptions yet.", loadError: "Commerce data could not be loaded.", formError: "The operation could not be completed.", amountHelp: "Enter major currency units; values are stored as minor units.", releasedAt: "Release date" }
} as const;
export function getCommerceDictionary(locale: Locale) { return commerceDictionaries[locale]; }
